In [32]:
from itertools import permutations
import numpy as np
import math

optimized burning progress, kl naive
/ k = number of sources
/ l = burning rounds

In [60]:
'''
A: an adj matrix that decribes a graph


returns the burning number of the graph described by A
'''
def burning_number_limited(A, k, l):
    n = len(A[0])
    if k >= n:
        return True
    #k = int(math.ceil(math.sqrt(n)))
    p = []
    for i in range(n):
        p.append(i)
    for i in permutations(p, k):
        #print("sequence: ", i)
        if burning(A, l, i):
            return True
    return False

In [62]:
#burning process based on B

def burning(A, l, burning_sequence):
    #keep a burning list that keeps tracks of the burning state of vertices
    #iterate through the burning sequence
    #for each source, determine the vertices it will burn in k rounds and update bl
    #at the end of each loop, check bl if all vertices is burned, if not return false.
    r = l
    n = len(A[0])
    bl = np.zeros(n)
    for x in burning_sequence: # for each source
        #bl[x] = 1
        #print('source', x)#............................................................
        #bl = np.copy(bv)
        if 0 in bl: 
            B = matrix_B(A,r)
            for i in range(len(B[x])):
                if B[x][i] == 1:
                    bl[i] = 1
            r -= 1
        else:
            #print('burned at', x)
            return True
    if 0 in bl: # if the graph is not yet burnt
        return False
    return True

In [53]:
from numpy.linalg import matrix_power
import numpy as np

def matrix_B(A,k):    # compute B = A + A^2 + A^3 + ... + A^k
    #A = A.todense()
    A = np.array(A)
    n = A.shape[0]
    B = np.zeros(A.shape)   # B is a 2D array
    for i in range(k):
        B += matrix_power(A,i+1)
    for i in range(n):
        for j in range(n):
            if B[i][j] > 0:
                B[i][j] = 1
    return B

def max_row(B):    # return the row with max sum
    num = 0
    maxrow = 0
    for i in range(B.shape[0]):
        if np.sum(B[i]) > num:
            num = np.sum(B[i])
            maxrow = i
    return maxrow

In [36]:
# '''

# to see if a graph can be burned with h vertices(all start to burn at 1st round) in k rounds

# '''

# def burninghl(A, h, k):
#     B = matrix_B(A,k)
#     for i in range(h):
#         p.append(i)
#     for i in permutations(p):
#         vertical = []
#         for j in range(h):
#             print(type(i[j])
#             #vertical += B [,;i[j]]
#         if not 0 in vertial:
#             return True
#     return False

In [37]:
# '''
# test1
# '''
# B = [[0,1,0,0,0,0], # a path with 6 nodes
#      [1,0,1,0,0,0],
#      [0,1,0,1,0,0],
#      [0,0,1,0,1,0],
#      [0,0,0,1,0,1],
#      [0,0,0,0,1,0]]

# burning_number_limited(B, 3)

In [73]:
'''
test2
'''
#test run time

import time

start = time.time()

# a path with n nodes
n = 30
A = np.zeros((n,n)) 
for i in range(n):
    for j in range(n):
        if abs(i - j) == 1:
            A[i][j] = 1
            

print("result: ", burning_number_limited(A, 3, 7))
end = time.time()
print("runtime: ", end - start)

result:  True
runtime:  0.4520740509033203


In [54]:
A = np.zeros((n,n)) 
for i in range(n):
    for j in range(n):
        if abs(i - j) == 1:
            A[i][j] = 1
            
print(A)
print(matrix_B(A,3))

[[0. 1. 0. 0. 0.]
 [1. 0. 1. 0. 0.]
 [0. 1. 0. 1. 0.]
 [0. 0. 1. 0. 1.]
 [0. 0. 0. 1. 0.]]
[[1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]]


In [70]:
#test run time

import time

start = time.time()
burning_number_limited(A, 3, 7)
end = time.time()
print(end - start)

0.4521830081939697
